import 'dart:async';
import 'package:dyte_uikit/dyte_uikit.dart';
import 'package:flutter/foundation.dart';

class DyteService {
  static final DyteService _instance = DyteService._internal();
  factory DyteService() => _instance;
  DyteService._internal();

  DyteMeetingInfoV2? _meetingInfo;
  bool _isInitialized = false;
  
  // Stream controllers for callbacks
  final StreamController<bool> _connectionController = StreamController<bool>.broadcast();

  // Getters
  DyteMeetingInfoV2? get meetingInfo => _meetingInfo;
  bool get isInitialized => _isInitialized;
  
  Stream<bool> get connectionStream => _connectionController.stream;

  /// Initialize Dyte meeting with auth token
  Future<bool> initializeMeeting({
    required String authToken,
    String? roomName,
    String? participantName,
    String? participantId,
  }) async {
    try {
      if (_isInitialized) {
        await dispose();
      }

      // Create meeting info using the new UI Kit approach
      _meetingInfo = DyteMeetingInfoV2(authToken: authToken);
      
      _isInitialized = true;
      _connectionController.add(true);
      
      if (kDebugMode) {
        print('Dyte meeting initialized successfully');
      }
      
      return true;
    } catch (e) {
      if (kDebugMode) {
        print('Error initializing Dyte meeting: $e');
      }
      _connectionController.add(false);
      return false;
    }
  }

  /// Dispose resources
  Future<void> dispose() async {
    try {
      _meetingInfo = null;
      _isInitialized = false;
      
      await _connectionController.close();
    } catch (e) {
      if (kDebugMode) {
        print('Error disposing Dyte service: $e');
      }
    }
  }

  /// Generate auth token (this should be done on your backend)
  /// For demo purposes, we'll return a placeholder
  static String generateAuthToken({
    required String roomName,
    required String participantName,
    String? participantId,
  }) {
    // In a real app, this should be generated by your backend
    // This is just a placeholder for demo purposes
    return 'demo_auth_token_${DateTime.now().millisecondsSinceEpoch}';
  }

  /// Create meeting room (this should be done on your backend)
  /// For demo purposes, we'll return a placeholder room name
  static String generateRoomName() {
    // In a real app, this should be created by your backend
    // This is just a placeholder for demo purposes
    return 'room_${DateTime.now().millisecondsSinceEpoch}';
  }
}
